/**
 Please work on p9 on page 282

 Guess the Number

Design a number guessing game program.
 The program should generate a random number and then ask the user to guess the number.
 Each time the user enters their guess, the program should indicate whether it was too high or too low.
 The game is over when the user correctly guesses the number.
 When the game ends, the program should display the number of guesses that the user made.

Test Case: The number (x) generated by Random Number Generator should be in an interval of 1 and 50 [1 <= x <= 50].


 *
      Prolog
 * a. Program Description
      This program will generate a number that matches the number which the user entered.
      If matched, the program will give the correct info.
      If the number that user entered is higher or lower than this program, and gives the info.
      The program will continue guessing until the user cancels

 * b. Author
        Genhai Yu
 * c. Date and time
 *      01/27/2025
 * d. Input variable
    float number_guest_guess = 0;

 * e. Process Flow
    Each time the number that the program generated is random.
    And process is matching the number that user entered with the number that program generated.

    Whether the number of user entered is higher or lower than the number that program generated both give the prompt.

    Program will continue guessing util user cancel.

 * f. Out variable

    If the number that user entered lower or higher and matched, and all of these conditions will give the prompt.
 */

#include "iostream"
#include "cstdlib"
#include <ctime>

using namespace std;


int main() {

    while (true) {

        // Initialize random seed each time
        srand(time(0));

        float number_guest_guess = 0;
        cout << "Please enter the number that you want to guess: ";
        cin >> number_guest_guess;

        // The number (x) generated by Random Number Generator should be in an interval of 1 and 50 [1 <= x <= 50].
        float g1 = rand() % 50 + 1;

        if (number_guest_guess < 0) {
            cout << "Error: Not a positive number." << endl;
            continue;
        }

        if (number_guest_guess == g1) {
            cout << "The number that you guess is : " << number_guest_guess << ", and is correct." << endl;
        } else if (number_guest_guess > g1) {
            cout << "The number that you guess is higher than this program." << endl;
        } else if (number_guest_guess < g1) {
            cout << "The number that you guess is lower than this program." << endl;
        }

        cout << "Do you want to continue (y/n)? ";

        string ans;
        cin >> ans;
        if (ans != "y") {
            cout << "Thank you for using this application, bye!" << endl;
            break;
        }
    }

    return 0;
}
